### ISSUE TITLE
Cuid standard is deprecated.

### ISSUE THREAD

**Issue by ericelliott** [hden/cuid#26]
Due to security concerns (which also exist in database auto-increment ids, uuid/guid, and most other id standrads), the Cuid standard is now deprecated in favor of [Cuid2](https://github.com/paralleldrive/cuid2).

**Comment by hden** [comment]
Got it. I'll implement v2 as soon as possible.

**Comment by hden** [comment]
Thanks for reaching out.
Implemented here https://github.com/hden/cuid2

**Comment by ericelliott** [comment]
Added to [ports](https://github.com/paralleldrive/cuid2#ports) 🎉
